#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "ezbookkeeping"
name = "ezBookkeeping"
description.en = "Self-hosted personal finance app"
description.fr = "Gestion financière personnelle"

version = "0.10.0~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "MIT"
website = "https://ezbookkeeping.mayswind.net/"
demo ="https://ezbookkeeping-demo.mayswind.net/"
admindoc = "https://ezbookkeeping.mayswind.net/"
code = "https://github.com/mayswind/ezbookkeeping"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/ezbookkeeping"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    in_subdir = false
    url = "https://github.com/mayswind/ezbookkeeping/releases/download/v0.10.0/ezbookkeeping-0.10.0-linux-amd64.tar.gz"
    sha256 = "1801f84ed0e44c9c5f977c0beb41d6f42aa992f92dd482128c09bdb1e8ca8f09"

    # autoupdate.strategy = "latest_github_tag"

    [resources.system_user]
    allow_email = true

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]

    [resources.apt]
    packages = "postgresql"

    [resources.database]
    type = "postgresql"
